/**
 * Living commission grades for Admin Widget Gallery badges.
 * Updated during full widget commission batches (Jul 2026).
 */
export type CommissionGrade = 'Pass' | 'Fix' | 'Defer'

export type CommissionEntry = {
  grade: CommissionGrade
  family: 'status' | 'oee' | 'downtime' | 'production' | 'layout'
  notes: string
}

export const COMMISSION_GRADES: Record<string, CommissionEntry> = {
  // —— status ——
  'status-light': { grade: 'Pass', family: 'status', notes: 'statusStyle matrix; calm beacon' },
  'run-state-badge': { grade: 'Pass', family: 'status', notes: 'statusStyle + context line' },
  'andon-stack': { grade: 'Pass', family: 'status', notes: 'tower/strip/beacon; frameVariant honored' },
  'oee-traffic-light': { grade: 'Pass', family: 'status', notes: 'soft panel/ring; no solid slab' },
  'line-status-indicator': { grade: 'Pass', family: 'status', notes: 'statusStyle; hierarchy mock in audit gallery' },
  'line-status-strip': { grade: 'Pass', family: 'status', notes: 'horizontal pills; hierarchy mock wired' },
  'connection-stale': { grade: 'Pass', family: 'status', notes: 'connection indicator' },
  'last-update-clock': { grade: 'Pass', family: 'status', notes: 'last snapshot clock' },
  'fault-banner': { grade: 'Pass', family: 'status', notes: 'alert strip; wall calm variant' },
  'state-timeline': { grade: 'Pass', family: 'status', notes: 'state timeline strip' },
  'state-distribution': { grade: 'Pass', family: 'status', notes: 'state time donut' },
  'state-time-breakdown': { grade: 'Pass', family: 'status', notes: 'state minutes breakdown' },
  'plant-grid': { grade: 'Pass', family: 'status', notes: 'line KPI card grid; audit hierarchy mock' },
  'machine-grid': { grade: 'Pass', family: 'status', notes: 'machine tiles; cardStyle flavor; audit hierarchy mock' },

  // —— oee ——
  'oee-gauge': { grade: 'Pass', family: 'oee', notes: 'KPI field picker; label below ring' },
  'oee-hero': { grade: 'Pass', family: 'oee', notes: 'KPI field + showLabelBelow' },
  'factor-gauge': { grade: 'Pass', family: 'oee', notes: 'A/P/Q single ring; oeeColor fallback fixed' },
  'apq-cluster': { grade: 'Pass', family: 'oee', notes: 'three rings' },
  'plant-summary-hero': { grade: 'Pass', family: 'oee', notes: 'KPI Summary; machine/line/plant scope' },
  'kpi-tile': { grade: 'Pass', family: 'oee', notes: '9 presentation skins + colorMode' },
  'kpi-stat-card': { grade: 'Pass', family: 'oee', notes: 'PresentationKpi + colorMode + wall label' },
  'scrap-tile': { grade: 'Pass', family: 'oee', notes: 'presentation skins' },
  'yield-tile': { grade: 'Pass', family: 'oee', notes: 'presentation skins' },
  'fpy-tile': { grade: 'Pass', family: 'oee', notes: 'presentation skins' },
  'teep-tile': { grade: 'Pass', family: 'oee', notes: 'presentation skins' },
  'linear-gauge': { grade: 'Pass', family: 'oee', notes: 'PresentationKpi gauge/bar/ring + colorMode' },
  'gap-cluster': { grade: 'Pass', family: 'oee', notes: 'A/P/Q gap vs target' },
  'target-vs-actual': { grade: 'Pass', family: 'oee', notes: 'bars vs targets' },
  'oee-waterfall': { grade: 'Pass', family: 'oee', notes: 'loss bridge; resolveScopedSnapshot' },
  'oee-by-shift': { grade: 'Pass', family: 'oee', notes: 'shift compare chart' },
  'line-leaderboard': { grade: 'Pass', family: 'oee', notes: 'OEE ranking bars' },
  'worst-lines': { grade: 'Pass', family: 'oee', notes: 'at-risk lines' },

  // —— downtime ——
  'downtime-list': { grade: 'Pass', family: 'downtime', notes: 'event table' },
  'pareto': { grade: 'Pass', family: 'downtime', notes: 'combo pareto' },
  'losses-donut': { grade: 'Pass', family: 'downtime', notes: 'six big losses' },
  'reliability-panel': { grade: 'Pass', family: 'downtime', notes: 'MTTR/MTBF panel' },
  'reliability-cluster': { grade: 'Pass', family: 'downtime', notes: 'reliability KPI cluster' },
  'mttr-tile': { grade: 'Pass', family: 'downtime', notes: 'presentation skins; snapshot fallback' },
  'mtbf-tile': { grade: 'Pass', family: 'downtime', notes: 'presentation skins; snapshot fallback' },
  'mttf-tile': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'mttd-tile': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'mean-lost-time': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'failure-rate': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'stops-per-hour': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'micro-stop-counter': { grade: 'Pass', family: 'downtime', notes: 'presentation skins' },
  'planned-unplanned-split': { grade: 'Pass', family: 'downtime', notes: 'split chart' },
  'top-fault-codes': { grade: 'Pass', family: 'downtime', notes: 'reason ranking' },
  'fault-code-summary': { grade: 'Pass', family: 'downtime', notes: 'reason cards' },
  'downtime-heatmap': { grade: 'Pass', family: 'downtime', notes: 'hour/day heat' },
  'event-feed': { grade: 'Pass', family: 'downtime', notes: 'live feed' },
  'loss-minutes-bridge': { grade: 'Pass', family: 'downtime', notes: 'loss bridge' },
  'time-balance': { grade: 'Pass', family: 'downtime', notes: 'available vs lost' },
  'operator-downtime-leaderboard': { grade: 'Pass', family: 'downtime', notes: 'operator ranking' },
  histogram: { grade: 'Pass', family: 'downtime', notes: 'duration buckets' },
  'active-downtime-timer': { grade: 'Pass', family: 'downtime', notes: 'Down/Setup only; Idle not treated as stop' },
  'reliability-trend': { grade: 'Pass', family: 'downtime', notes: 'historian trend' },
  'loss-trend': { grade: 'Pass', family: 'downtime', notes: 'loss trend' },
  'unassigned-stops-banner': { grade: 'Pass', family: 'downtime', notes: 'unassigned banner' },
  'unattributed-downtime-counter': { grade: 'Pass', family: 'downtime', notes: 'awaiting reason count' },

  // —— production ——
  'count-tile': { grade: 'Pass', family: 'production', notes: 'presentation skins' },
  'total-count-tile': { grade: 'Pass', family: 'production', notes: 'PresentationKpi skins' },
  'throughput-tile': { grade: 'Pass', family: 'production', notes: 'presentation skins' },
  'cycle-time-tile': { grade: 'Pass', family: 'production', notes: 'presentation skins' },
  'units-per-shift': { grade: 'Pass', family: 'production', notes: 'PresentationKpi skins' },
  'sparkline-tile': { grade: 'Pass', family: 'production', notes: 'PresentationKpi spark modes' },
  'hourly-production-bar': { grade: 'Pass', family: 'production', notes: 'hourly bars' },
  'scrap-trend': { grade: 'Pass', family: 'production', notes: 'scrap trend' },
  'production-vs-target': { grade: 'Pass', family: 'production', notes: 'vs target trend' },
  'time-series-trend': { grade: 'Pass', family: 'production', notes: 'bound field trend' },
  'multi-trend': { grade: 'Pass', family: 'production', notes: 'multi series' },
  'speed-trend': { grade: 'Pass', family: 'production', notes: 'speed trend' },
  'shift-summary': { grade: 'Pass', family: 'production', notes: 'shift summary' },
  'shift-progress': { grade: 'Pass', family: 'production', notes: 'scoped shift progress' },
  'shift-progress-bar': { grade: 'Pass', family: 'production', notes: 'scoped progress bar' },
  'shift-context-strip': { grade: 'Pass', family: 'production', notes: 'shift context' },
  'attainment-tile': { grade: 'Pass', family: 'production', notes: 'run/shift attainment' },
  'current-job-banner': { grade: 'Pass', family: 'production', notes: 'active job; scoped snapshot' },
  'production-run-list': { grade: 'Pass', family: 'production', notes: 'run list' },
  'count-to-target': { grade: 'Pass', family: 'production', notes: 'count progress' },
  'count-to-go': { grade: 'Pass', family: 'production', notes: 'remaining count' },
  'target-pace-tile': { grade: 'Pass', family: 'production', notes: 'required pace' },
  'pace-gauge': { grade: 'Pass', family: 'production', notes: 'pace indicator' },
  'cycle-time-compare': { grade: 'Pass', family: 'production', notes: 'ideal vs actual' },
  'rate-variance': { grade: 'Pass', family: 'production', notes: 'rate variance' },
  'takt-vs-actual': { grade: 'Pass', family: 'production', notes: 'takt compare' },
  'expected-vs-actual-count': { grade: 'Pass', family: 'production', notes: 'expected vs actual' },
  'parts-loss-waterfall': { grade: 'Pass', family: 'production', notes: 'parts loss bridge' },
  'recipe-product-strip': { grade: 'Pass', family: 'production', notes: 'recipe context' },
  'shift-comparison-card': { grade: 'Pass', family: 'production', notes: 'shift compare card' },

  // —— layout ——
  'live-tag-value': { grade: 'Pass', family: 'layout', notes: 'PLC tag display' },
  'text-label': { grade: 'Pass', family: 'layout', notes: 'static text' },
  'rich-notes': { grade: 'Pass', family: 'layout', notes: 'notes block' },
  'image-logo': { grade: 'Pass', family: 'layout', notes: 'image/logo' },
  divider: { grade: 'Pass', family: 'layout', notes: 'section divider; no frame variants' },
  'clock-date': { grade: 'Pass', family: 'layout', notes: 'clock' },
  'marquee-ticker': { grade: 'Pass', family: 'layout', notes: 'ticker' },
  'qr-link-tile': { grade: 'Pass', family: 'layout', notes: 'QR link' },
  'dashboard-link': { grade: 'Pass', family: 'layout', notes: 'nav to dashboard; placeholder id until set' },
  'navigation-drill': { grade: 'Pass', family: 'layout', notes: 'nav drill' },
  'udt-member-value': { grade: 'Pass', family: 'layout', notes: 'UDT member' },
  'iframe-embed': { grade: 'Pass', family: 'layout', notes: 'iframe; demo URL may fail offline' },
  'quick-links-bar': { grade: 'Pass', family: 'layout', notes: 'quick links' },
  'data-table': { grade: 'Pass', family: 'layout', notes: 'data table; audit hierarchy mock' },
  'top-n-table': { grade: 'Pass', family: 'layout', notes: 'top N table; audit hierarchy mock' },
  'drill-through-list': { grade: 'Pass', family: 'layout', notes: 'drill list' },
  'kpi-tile-group': { grade: 'Pass', family: 'layout', notes: 'KPI group' },
  'operator-downtime-pad': { grade: 'Pass', family: 'layout', notes: 'writes when allowInteractiveWrites + permission' },
  'fault-ack-button': { grade: 'Pass', family: 'layout', notes: 'writes when allowInteractiveWrites + PlcWrite' },
  'plc-write-controls': { grade: 'Pass', family: 'layout', notes: 'writes when allowInteractiveWrites + PlcWrite' },
  'container-panel': { grade: 'Pass', family: 'layout', notes: 'nested CSS/RGL host; one level' },
  'tabbed-panel': { grade: 'Pass', family: 'layout', notes: 'tabbed nested host; one level' },
}
