using System.Net;
using System.Net.Mail;
using ConnectOEE.Core;
using ConnectOEE.Core.Entities;
using ConnectOEE.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace ConnectOEE.Reporting;

/// <summary>Delivers a generated report via SMTP email or a file-drop folder.</summary>
public class ReportDeliveryService
{
    private readonly ConnectOeeDbContext _db;

    public ReportDeliveryService(ConnectOeeDbContext db) => _db = db;

    public async Task DeliverAsync(ReportSchedule schedule, GeneratedReport report, CancellationToken ct = default)
    {
        switch (schedule.DeliveryMethod)
        {
            case ReportDeliveryMethod.FileDrop:
                await FileDropAsync(schedule, report, ct);
                break;
            case ReportDeliveryMethod.Email:
            default:
                await EmailAsync(schedule, report, ct);
                break;
        }
    }

    private static async Task FileDropAsync(ReportSchedule schedule, GeneratedReport report, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(schedule.FileDropPath))
            throw new InvalidOperationException("File drop path is not configured for this schedule.");

        Directory.CreateDirectory(schedule.FileDropPath);
        var target = Path.Combine(schedule.FileDropPath, report.FileName);
        await File.WriteAllBytesAsync(target, report.Content, ct);
    }

    private async Task EmailAsync(ReportSchedule schedule, GeneratedReport report, CancellationToken ct)
    {
        var smtp = await _db.SmtpSettings.AsNoTracking().FirstOrDefaultAsync(ct)
            ?? throw new InvalidOperationException("SMTP is not configured (Admin → Reports → SMTP).");

        var recipients = (schedule.Recipients ?? string.Empty)
            .Split(new[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (recipients.Length == 0)
            throw new InvalidOperationException("No recipients configured for this schedule.");

        using var message = new MailMessage
        {
            From = new MailAddress(smtp.FromAddress, smtp.FromName),
            Subject = $"{report.Model.Title} — {report.Model.ScopeName}",
            Body =
                $"Attached: {report.Model.Title} for {report.Model.ScopeLevel} '{report.Model.ScopeName}'.\n" +
                $"Period: {report.Model.From.ToLocalTime():g} – {report.Model.To.ToLocalTime():g}\n" +
                $"OEE {report.Model.Oee.OeePct:0.0}% · Good {report.Model.GoodCount:n0} · Reject {report.Model.RejectCount:n0}\n\n" +
                "Generated by ConnectOEE.",
        };
        foreach (var r in recipients) message.To.Add(r);
        message.Attachments.Add(new Attachment(new MemoryStream(report.Content), report.FileName, report.ContentType));

        using var client = new SmtpClient(smtp.Host, smtp.Port) { EnableSsl = smtp.UseSsl };
        if (!string.IsNullOrEmpty(smtp.Username))
            client.Credentials = new NetworkCredential(smtp.Username, smtp.Password);

        await client.SendMailAsync(message, ct);
    }

    public async Task SendTestEmailAsync(string recipient, CancellationToken ct = default)
    {
        var smtp = await _db.SmtpSettings.AsNoTracking().FirstOrDefaultAsync(ct)
            ?? throw new InvalidOperationException("SMTP is not configured.");

        using var message = new MailMessage
        {
            From = new MailAddress(smtp.FromAddress, smtp.FromName),
            Subject = "ConnectOEE SMTP test",
            Body = "This is a test message from ConnectOEE report delivery.\n\nIf you received this, SMTP is configured correctly.",
        };
        message.To.Add(recipient);

        using var client = new SmtpClient(smtp.Host, smtp.Port) { EnableSsl = smtp.UseSsl };
        if (!string.IsNullOrEmpty(smtp.Username))
            client.Credentials = new NetworkCredential(smtp.Username, smtp.Password);

        await client.SendMailAsync(message, ct);
    }
}
