import type { MetricHelpEntry } from './types'

/** Glossary keyed by SNAPSHOT_FIELDS value. Source: docs/06-oee-engine-metrics.md */
export const METRIC_HELP: Record<string, MetricHelpEntry> = {
  oeePct: {
    id: 'oeePct',
    title: 'OEE %',
    summary: 'Overall Equipment Effectiveness — good parts at ideal rate vs planned production time.',
    definition:
      'Combines availability, performance, and quality into one score for the current shift window. World-class targets are often 85%+ but vary by industry.',
    formula: 'OEE = Availability × Performance × Quality',
    unit: '%',
    related: ['availabilityPct', 'performancePct', 'qualityPct'],
    category: 'oee',
    caveats: ['Uses ConnectOEE shift counts and ideal cycle from active product/recipe/line config.'],
  },
  availabilityPct: {
    id: 'availabilityPct',
    title: 'Availability %',
    summary: 'Share of planned production time the line was actually running.',
    definition: 'Measures downtime losses — how much of scheduled production time was lost to stops.',
    formula: 'Availability = Run time ÷ Planned production time',
    unit: '%',
    related: ['oeePct', 'availabilityLossMin', 'plannedDowntimeMin', 'unplannedDowntimeMin'],
    category: 'oee',
  },
  performancePct: {
    id: 'performancePct',
    title: 'Performance %',
    summary: 'How fast the line ran vs ideal cycle time while operating.',
    definition:
      'Compares ideal time needed for actual output against actual run time. Capped at 100% — brief over-speed from sensor timing is clipped.',
    formula: 'Performance = min(1, (Ideal cycle × Total count) ÷ Run time)',
    unit: '%',
    related: ['oeePct', 'performanceLossMin', 'idealCycleTimeSec', 'actualCycleTimeSec'],
    category: 'oee',
    caveats: ['Ideal cycle resolves: LineProductRate → ProductRecipe → line OeeConfig default.'],
  },
  qualityPct: {
    id: 'qualityPct',
    title: 'Quality %',
    summary: 'Good parts as a share of total parts produced this shift.',
    definition: 'Quality losses come from rejects and scrap during the shift window.',
    formula: 'Quality = Good count ÷ Total count',
    unit: '%',
    related: ['oeePct', 'qualityLossMin', 'scrapPct', 'yieldPct', 'fpyPct'],
    category: 'oee',
  },
  teepPct: {
    id: 'teepPct',
    title: 'TEEP %',
    summary: 'OEE adjusted for calendar utilization — includes time not scheduled for production.',
    definition: 'Total Effective Equipment Performance folds loading/calendar utilization into OEE.',
    formula: 'TEEP = OEE × (Planned time ÷ All calendar time)',
    unit: '%',
    related: ['oeePct'],
    category: 'oee',
  },
  goodCount: {
    id: 'goodCount',
    title: 'Good count',
    summary: 'First-pass good parts counted by ConnectOEE this shift.',
    definition:
      'ConnectOEE owns shift totals from PLC deltas or pulse edges. Totals reset on shift boundary, not on PLC counter reset.',
    unit: 'parts',
    related: ['rejectCount', 'reworkCount', 'qualityPct'],
    category: 'production',
  },
  rejectCount: {
    id: 'rejectCount',
    title: 'Reject count',
    summary: 'Rejected/scrap parts counted this shift.',
    definition: 'Same ingest rules as good count — cumulative delta or pulse from mapped reject signal.',
    unit: 'parts',
    related: ['goodCount', 'scrapPct'],
    category: 'production',
  },
  reworkCount: {
    id: 'reworkCount',
    title: 'Rework count',
    summary: 'Parts sent to rework this shift.',
    definition: 'Used in first-pass yield (FPY). Good count should represent first-pass good only.',
    unit: 'parts',
    related: ['fpyPct', 'goodCount'],
    category: 'production',
  },
  scrapPct: {
    id: 'scrapPct',
    title: 'Scrap %',
    summary: 'Reject share of total production.',
    formula: 'Scrap = Reject count ÷ Total count',
    unit: '%',
    related: ['rejectCount', 'qualityPct'],
    category: 'production',
  },
  yieldPct: {
    id: 'yieldPct',
    title: 'Yield %',
    summary: 'Same as quality — good parts over total produced.',
    formula: 'Yield = Good count ÷ Total count',
    unit: '%',
    related: ['qualityPct'],
    category: 'production',
  },
  fpyPct: {
    id: 'fpyPct',
    title: 'FPY %',
    summary: 'First-pass yield — good parts that did not require rework.',
    formula: 'FPY = Good ÷ (Good + Reject + Rework)',
    unit: '%',
    related: ['goodCount', 'reworkCount'],
    category: 'production',
    caveats: ['Good count should be first-pass only for FPY to be meaningful.'],
  },
  mttrMin: {
    id: 'mttrMin',
    title: 'MTTR',
    summary: 'Mean Time To Repair — average duration per downtime stop.',
    definition: 'Includes planned and unplanned stops in the average down duration.',
    formula: 'MTTR = Total downtime ÷ Number of stops',
    unit: 'min',
    related: ['mtbfMin', 'availabilityFromReliabilityPct', 'meanLostTimePerDowntimeMin'],
    category: 'reliability',
  },
  mtbfMin: {
    id: 'mtbfMin',
    title: 'MTBF',
    summary: 'Mean Time Between Failures — average uptime between unplanned failures.',
    definition: 'Failures are unplanned stops only. Planned downtime is excluded from the failure count.',
    formula: 'MTBF = Total uptime ÷ Number of unplanned failures',
    unit: 'min',
    related: ['mttrMin', 'failureCount', 'failureRatePerHour'],
    category: 'reliability',
  },
  mttfMin: {
    id: 'mttfMin',
    title: 'MTTF',
    summary: 'Mean Time To Failure — uptime framing for first-failure analysis.',
    definition: 'In ConnectOEE this uses the same calculation as MTBF (uptime ÷ unplanned failures).',
    formula: 'MTTF = Total uptime ÷ Number of unplanned failures',
    unit: 'min',
    related: ['mtbfMin'],
    category: 'reliability',
    caveats: ['Currently identical to MTBF in the engine.'],
  },
  mttdMin: {
    id: 'mttdMin',
    title: 'MTTD',
    summary: 'Mean Time To Detect — average time from stop start to operator acknowledgment.',
    formula: 'MTTD = Average(Acknowledged time − Stop start time)',
    unit: 'min',
    related: ['downtimeCount'],
    category: 'reliability',
    caveats: [
      'Live snapshots show 0 until an operator enters a downtime reason (which sets acknowledgment).',
      'Historical/API views include acknowledged events only.',
    ],
  },
  meanLostTimePerDowntimeMin: {
    id: 'meanLostTimePerDowntimeMin',
    title: 'Mean lost time',
    summary: 'Average lost production time per stop.',
    definition: 'Documented as mean lost time per downtime event. Currently equals MTTR in the engine.',
    formula: 'Mean lost time = Total downtime ÷ Number of stops',
    unit: 'min',
    related: ['mttrMin'],
    category: 'reliability',
  },
  failureRatePerHour: {
    id: 'failureRatePerHour',
    title: 'Failure rate',
    summary: 'Unplanned failures per hour of uptime.',
    formula: 'Failure rate = Unplanned failures ÷ Uptime hours',
    unit: '/hr',
    related: ['mtbfMin', 'failureCount'],
    category: 'reliability',
  },
  stopsPerHour: {
    id: 'stopsPerHour',
    title: 'Stops / hr',
    summary: 'All downtime stops (planned + unplanned) per calendar hour in the window.',
    formula: 'Stops/hr = Total stops ÷ Period hours',
    unit: '/hr',
    related: ['downtimeCount', 'microStopCount'],
    category: 'reliability',
  },
  availabilityFromReliabilityPct: {
    id: 'availabilityFromReliabilityPct',
    title: 'Availability (reliability) %',
    summary: 'Availability derived from MTBF and MTTR instead of run/planned time.',
    formula: 'Availability = MTBF ÷ (MTBF + MTTR)',
    unit: '%',
    related: ['mtbfMin', 'mttrMin'],
    category: 'reliability',
    caveats: ['MTTR uses all stops; MTBF uses unplanned failures only.'],
  },
  downtimeCount: {
    id: 'downtimeCount',
    title: 'Downtime count',
    summary: 'Number of downtime events in the shift window.',
    unit: 'stops',
    related: ['stopsPerHour', 'microStopCount'],
    category: 'operational',
  },
  microStopCount: {
    id: 'microStopCount',
    title: 'Micro-stop count',
    summary: 'Short stops below the configured micro-stop threshold.',
    definition: 'Threshold is set per line in OEE config. Micro-stops still count toward downtime.',
    related: ['downtimeCount', 'stopsPerHour'],
    category: 'operational',
  },
  failureCount: {
    id: 'failureCount',
    title: 'Failure count',
    summary: 'Unplanned downtime events only.',
    related: ['mtbfMin', 'failureRatePerHour'],
    category: 'reliability',
  },
  uptimeMin: {
    id: 'uptimeMin',
    title: 'Uptime',
    summary: 'Minutes the line was running this shift.',
    unit: 'min',
    related: ['downtimeMin', 'uptimePct'],
    category: 'operational',
  },
  downtimeMin: {
    id: 'downtimeMin',
    title: 'Downtime',
    summary: 'Total minutes stopped this shift (planned + unplanned).',
    unit: 'min',
    related: ['plannedDowntimeMin', 'unplannedDowntimeMin'],
    category: 'operational',
  },
  plannedDowntimeMin: {
    id: 'plannedDowntimeMin',
    title: 'Planned downtime',
    summary: 'Scheduled stops such as changeovers and planned maintenance.',
    unit: 'min',
    related: ['unplannedDowntimeMin'],
    category: 'operational',
  },
  unplannedDowntimeMin: {
    id: 'unplannedDowntimeMin',
    title: 'Unplanned downtime',
    summary: 'Breakdowns and other unscheduled stops.',
    unit: 'min',
    related: ['plannedDowntimeMin', 'failureCount'],
    category: 'operational',
  },
  uptimePct: {
    id: 'uptimePct',
    title: 'Uptime %',
    summary: 'Running time as a share of running + downtime minutes this shift.',
    formula: 'Uptime % = Uptime min ÷ (Uptime min + Downtime min)',
    unit: '%',
    related: ['uptimeMin', 'downtimeMin'],
    category: 'operational',
  },
  availabilityLossMin: {
    id: 'availabilityLossMin',
    title: 'Availability loss',
    summary: 'Minutes lost to downtime (planned production time not spent running).',
    formula: 'Availability loss = max(0, Planned time − Run time)',
    unit: 'min',
    related: ['availabilityPct'],
    category: 'loss',
  },
  performanceLossMin: {
    id: 'performanceLossMin',
    title: 'Performance loss',
    summary: 'Minutes lost to running slower than ideal rate.',
    formula: 'Performance loss = max(0, Run time − Ideal production time)',
    unit: 'min',
    related: ['performancePct'],
    category: 'loss',
  },
  qualityLossMin: {
    id: 'qualityLossMin',
    title: 'Quality loss',
    summary: 'Ideal production time lost to rejects.',
    formula: 'Quality loss = Ideal cycle × Reject count',
    unit: 'min',
    related: ['qualityPct'],
    category: 'loss',
  },
  actualCycleTimeSec: {
    id: 'actualCycleTimeSec',
    title: 'Actual cycle',
    summary: 'Average seconds per part while running.',
    formula: 'Actual cycle = Run time ÷ Total count',
    unit: 's',
    related: ['idealCycleTimeSec'],
    category: 'rate',
  },
  idealCycleTimeSec: {
    id: 'idealCycleTimeSec',
    title: 'Ideal cycle',
    summary: 'Target seconds per good part from product/line configuration.',
    related: ['performancePct', 'actualCycleTimeSec'],
    unit: 's',
    category: 'rate',
  },
  actualRatePph: {
    id: 'actualRatePph',
    title: 'Actual rate',
    summary: 'Parts per hour based on actual run time and count.',
    formula: 'Actual rate = Total count ÷ Run time hours',
    unit: 'pph',
    related: ['idealRatePph', 'rateVariancePct'],
    category: 'rate',
  },
  idealRatePph: {
    id: 'idealRatePph',
    title: 'Ideal rate',
    summary: 'Target parts per hour from ideal cycle time.',
    formula: 'Ideal rate = 3600 ÷ Ideal cycle (sec)',
    unit: 'pph',
    related: ['actualRatePph'],
    category: 'rate',
  },
  rateVariancePct: {
    id: 'rateVariancePct',
    title: 'Rate variance',
    summary: 'How far actual rate deviates from ideal rate.',
    formula: 'Rate variance = (Actual − Ideal) ÷ Ideal × 100',
    unit: '%',
    related: ['actualRatePph', 'idealRatePph'],
    category: 'rate',
  },
  targetOeePct: {
    id: 'targetOeePct',
    title: 'OEE target',
    summary: 'Line-configured OEE goal from Admin → Hierarchy.',
    definition: 'Used for gap metrics and target-vs-actual widgets. Defaults to 85% when unset.',
    unit: '%',
    related: ['oeeGapPct', 'oeePct'],
    category: 'oee',
  },
  targetAvailabilityPct: {
    id: 'targetAvailabilityPct',
    title: 'Availability target',
    summary: 'Line-configured availability goal.',
    unit: '%',
    related: ['availabilityGapPct', 'availabilityPct'],
    category: 'oee',
  },
  targetPerformancePct: {
    id: 'targetPerformancePct',
    title: 'Performance target',
    summary: 'Line-configured performance goal.',
    unit: '%',
    related: ['performanceGapPct', 'performancePct'],
    category: 'oee',
  },
  targetQualityPct: {
    id: 'targetQualityPct',
    title: 'Quality target',
    summary: 'Line-configured quality goal.',
    unit: '%',
    related: ['qualityGapPct', 'qualityPct'],
    category: 'oee',
  },
  oeeGapPct: {
    id: 'oeeGapPct',
    title: 'OEE gap',
    summary: 'Actual OEE minus the line OEE target.',
    formula: 'OEE gap = OEE % − Target OEE %',
    unit: '%',
    related: ['oeePct', 'targetOeePct'],
    category: 'oee',
    caveats: ['Negative values mean below target. Plant/line roll-ups recompute from rolled-up OEE vs target, not an average of machine gaps.'],
  },
  availabilityGapPct: {
    id: 'availabilityGapPct',
    title: 'Availability gap',
    summary: 'Actual availability minus the line availability target.',
    formula: 'Availability gap = Availability % − Target availability %',
    unit: '%',
    related: ['availabilityPct', 'targetAvailabilityPct'],
    category: 'oee',
  },
  performanceGapPct: {
    id: 'performanceGapPct',
    title: 'Performance gap',
    summary: 'Actual performance minus the line performance target.',
    formula: 'Performance gap = Performance % − Target performance %',
    unit: '%',
    related: ['performancePct', 'targetPerformancePct'],
    category: 'oee',
  },
  qualityGapPct: {
    id: 'qualityGapPct',
    title: 'Quality gap',
    summary: 'Actual quality minus the line quality target.',
    formula: 'Quality gap = Quality % − Target quality %',
    unit: '%',
    related: ['qualityPct', 'targetQualityPct'],
    category: 'oee',
  },
  utilizationPct: {
    id: 'utilizationPct',
    title: 'Utilization %',
    summary: 'Calendar loading factor — planned production time as a share of all time.',
    definition: 'Standalone TEEP loading metric. Does not replace OEE availability.',
    formula: 'Utilization = Planned production time ÷ All calendar time × 100',
    unit: '%',
    related: ['teepPct', 'oeePct'],
    category: 'oee',
  },
  cycleVariancePct: {
    id: 'cycleVariancePct',
    title: 'Cycle variance',
    summary: 'How far actual cycle time deviates from ideal cycle.',
    formula: 'Cycle variance = (Actual cycle − Ideal cycle) ÷ Ideal cycle × 100',
    unit: '%',
    related: ['actualCycleTimeSec', 'idealCycleTimeSec'],
    category: 'rate',
  },
  reworkPct: {
    id: 'reworkPct',
    title: 'Rework %',
    summary: 'Rework parts as a share of total production.',
    formula: 'Rework % = Rework ÷ (Good + Reject + Rework) × 100',
    unit: '%',
    related: ['reworkCount', 'fpyPct'],
    category: 'production',
    caveats: ['Shown only when line rework tracking is On or Auto with a mapped ReworkCount signal.'],
  },
  runAttainmentPct: {
    id: 'runAttainmentPct',
    title: 'Run attainment %',
    summary: 'Good parts produced vs the active order/SKU run target.',
    formula: 'Run attainment = Good count ÷ Run target × 100',
    unit: '%',
    related: ['runPartsRemaining', 'goodCount'],
    category: 'production',
    caveats: ['Run target resolves: ProductionRun → LineProductRate → ProductRecipe. Rejects do not count toward attainment.'],
  },
  shiftAttainmentPct: {
    id: 'shiftAttainmentPct',
    title: 'Shift attainment %',
    summary: 'Good parts vs the shift production schedule target.',
    formula: 'Shift attainment = Good count ÷ Shift target × 100',
    unit: '%',
    related: ['shiftPartsRemaining', 'goodCount'],
    category: 'production',
    caveats: ['Requires a ProductionSchedule row with TargetQuantity for the current shift window.'],
  },
  runPartsRemaining: {
    id: 'runPartsRemaining',
    title: 'Run parts remaining',
    summary: 'Parts still needed to hit the run target.',
    formula: 'Remaining = max(0, Run target − Good count)',
    unit: 'parts',
    related: ['runAttainmentPct'],
    category: 'production',
  },
  shiftPartsRemaining: {
    id: 'shiftPartsRemaining',
    title: 'Shift parts remaining',
    summary: 'Parts still needed to hit the shift schedule target.',
    formula: 'Remaining = max(0, Shift target − Good count)',
    unit: 'parts',
    related: ['shiftAttainmentPct'],
    category: 'production',
  },
  maxPossibleParts: {
    id: 'maxPossibleParts',
    title: 'Max possible parts',
    summary: 'Parts you could make at ideal rate during all planned production time in the window.',
    formula: 'floor(Planned time ÷ Ideal cycle)',
    unit: 'parts',
    related: ['expectedPartsPace', 'theoreticalOutput'],
    category: 'production',
  },
  expectedPartsPace: {
    id: 'expectedPartsPace',
    title: 'Expected parts (pace)',
    summary: 'Parts you should have produced by now at ideal rate × elapsed shift time.',
    formula: 'Ideal rate (pph) × elapsed shift hours',
    unit: 'parts',
    related: ['goodCount', 'maxPossibleParts'],
    category: 'production',
  },
  partsLostAvailability: {
    id: 'partsLostAvailability',
    title: 'Parts lost — downtime',
    summary: 'Production lost to availability (machine not running at ideal speed).',
    formula: 'Availability loss minutes × ideal rate ÷ 60',
    unit: 'parts',
    related: ['availabilityLossMin', 'partsLostBreakdown'],
    category: 'loss',
    caveats: ['Breakdown loss is a subset of this bucket when PLC reports Down state.'],
  },
  partsLostPerformance: {
    id: 'partsLostPerformance',
    title: 'Parts lost — slow running',
    summary: 'Production lost because the machine ran slower than ideal while still running.',
    formula: 'Performance loss minutes × ideal rate ÷ 60',
    unit: 'parts',
    related: ['performanceLossMin'],
    category: 'loss',
  },
  partsLostQuality: {
    id: 'partsLostQuality',
    title: 'Parts lost — quality',
    summary: 'Reject count — parts produced but scrapped.',
    formula: 'Reject count',
    unit: 'parts',
    related: ['rejectCount', 'scrapPct'],
    category: 'loss',
  },
  partsLostBreakdown: {
    id: 'partsLostBreakdown',
    title: 'Parts lost — breakdown',
    summary: 'Parts lost while machine was in Down (faulted) state at ideal rate.',
    formula: 'Down state seconds ÷ ideal cycle',
    unit: 'parts',
    related: ['downMin', 'partsLostAvailability'],
    category: 'loss',
    caveats: ['Subset of availability parts loss — do not add both when totaling.'],
  },
  partsCouldHaveMade: {
    id: 'partsCouldHaveMade',
    title: 'Could have made',
    summary: 'Good + all attributed parts losses (A + P + Q).',
    formula: 'Good + parts lost (downtime + slow + rejects)',
    unit: 'parts',
    related: ['goodCount', 'partsLostAvailability'],
    category: 'production',
  },
  idleMin: {
    id: 'idleMin',
    title: 'Idle time',
    summary: 'Minutes in Idle run state this shift.',
    unit: 'min',
    related: ['downMin', 'setupMin'],
    category: 'operational',
    caveats: ['Requires PLC to emit distinct Idle state. Single-bool lines may only show Running vs stopped.'],
  },
  downMin: {
    id: 'downMin',
    title: 'Breakdown time',
    summary: 'Minutes in Down (faulted) run state this shift.',
    unit: 'min',
    related: ['downtimeMin', 'idleMin'],
    category: 'operational',
    caveats: ['Distinct from total downtimeMin, which includes all non-running states.'],
  },
  setupMin: {
    id: 'setupMin',
    title: 'Setup time',
    summary: 'Minutes in Setup run state this shift.',
    unit: 'min',
    category: 'operational',
  },
  starvedMin: {
    id: 'starvedMin',
    title: 'Starved time',
    summary: 'Minutes waiting for upstream material.',
    unit: 'min',
    category: 'operational',
  },
  blockedMin: {
    id: 'blockedMin',
    title: 'Blocked time',
    summary: 'Minutes blocked by downstream constraints.',
    unit: 'min',
    category: 'operational',
  },
  state: {
    id: 'state',
    title: 'Run state',
    summary: 'Current machine state from the mapped run-state signal.',
    definition: 'Typical values: Running, Idle, Down, PlannedDown, Unknown.',
    category: 'operational',
  },
  speed: {
    id: 'speed',
    title: 'Rate (computed)',
    summary: 'Same as Actual rate — derived from shift counts and run time, not a PLC tag.',
    definition: 'Legacy field name; use actualRatePph. No Speed PLC mapping is required.',
    category: 'operational',
    related: ['actualRatePph'],
  },
  downtimeReason: {
    id: 'downtimeReason',
    title: 'Downtime reason',
    summary: 'Numeric PLC stop code and catalog description when the Downtime Reason tag is mapped.',
    definition: 'Unknown codes are auto-added to Admin → Downtime Reasons for supervisor review.',
    category: 'operational',
  },
}

export const METRIC_HELP_LIST = Object.values(METRIC_HELP)

export function getMetricHelp(id: string | undefined | null): MetricHelpEntry | undefined {
  if (!id) return undefined
  return METRIC_HELP[id]
}

export function hasMetricHelp(id: string | undefined | null): boolean {
  return !!getMetricHelp(id)
}
